clear all;
im=importdata('Sheet1.txt');
NN = 64;
image0 = permute(reshape((im),1,NN,NN),[3 2 1]);
%image0 = image(images(:,:,1)); 
%colormap(gray(256));
%figure;
imagesc(image0);
colormap(gray);
axis equal;
folder = uigetdir('C:\Users\dillo\Desktop\shg data\2022'); 
stackname=strcat(folder,'\','raster_image','.tif');
%stackedname=strcat(folder,'\','raster_384','.tif');
stackssname=strcat(folder,'\','raster_512','.tif');
% image=image0;
% image=(image-min(min(image)))/(max(max(image))-min(min(image)))*65536;
% Dimage=uint16(image);
% Eimage = imresize(Dimage, (384/NN), 'nearest');
%J = imadjust(Dimage,[0.001 .01],[.01 .99],.9);
% J = imadjust(image,[0 0.2],[0.5 1]);
% imwrite(J,stacksname);
% imwrite(Dimage,stackname);
% imwrite(Eimage,stackedname);
%M = min(min(image0));
imwrite(mat2gray(image0),stackname);
imwrite(imresize(mat2gray(image0),[512 512],'nearest'),stackssname);
% imwrite(J,stacksname);